language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - "2.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python -m doctest asciisketch.py
